### ISSUE TITLE
[EPIC] Callback URLs

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/user-api#1741]
**Is your feature request related to a problem? Please describe.**

Our current implementation of Kebechet relies on the adviser workflow to run Kebechet certain data is provided to the `user-api`. This creates a very tight coupling between the two services. User API should accept instead a callback URL as this allows for a more generic integration point.

See here: https://stackoverflow.com/a/54458707/11777392 for a more detailed explanation regarding callback URLs

**Describe the solution you'd like**
I as an integrating service, pass along a callback url to my API as well as the secret for my API (or some way of ensuring response is from Thoth). In response, Thoth will process my request and whenever it is done it will post the results to the provided callback url.

**Additional context**
This will not completely decouple the two services, as we rely on thoth-storages to store stack info and schedule adviser on package releases, etc... However, this information and processing **can** eventually be moved because all events are posted through Kafka. Kafka is already a valid integration point for clients inside the cluster, and could eventually be moved outside the cluster (https://banzaicloud.com/docs/supertubes/kafka-operator/external-listener/)

Tasks:
- [x] https://github.com/thoth-station/thoth-application/issues/2556
- [x] https://github.com/thoth-station/thoth-application/issues/2557
- [x] https://github.com/thoth-station/workflow-helpers/issues/396
- [x] https://github.com/thoth-station/thoth-application/issues/2558
- [x] https://github.com/thoth-station/user-api/issues/1756

**Comment by goern** [comment]
/assign @KPostOffice 
/priority important-soon

Kevin, please go ahead and start breaking down this mega-epic into more detailed issues and start refining/planning them...

**Comment by codificat** [comment]
Some more context: this was discussed in the [Thoth Tech Talk](https://bit.ly/thoth-tech-talk-sessions) yesterday, 2022-04-07 ([recording](https://youtu.be/qwpyzY1Sfto))

**Comment by KPostOffice** [comment]
Example flow diagram for adviser

```mermaid
flowchart TD
  sendAdvise[/Send advise/]
  resultExists{Does result already exist?}
  callback1{Is callback URL set?}
  callback2{Is callback URL set?}
  results2callback[Send results to callback URL]
  sendDocID[Send adviser document ID]
  adviseInProgress{Is advise in progress?}
  add2subscribers[Add callback to list of subscribers]
  scheduleAdvise[Schedule advise]
  sendAdvise --> resultExists;
  resultExists -- No --> adviseInProgress;
  resultExists -- Yes --> callback1;
  callback1 -- Yes --> results2callback;
  results2callback --> sendDocID;
  adviseInProgress -- No --> scheduleAdvise;
  adviseInProgress -- Yes --> callback2;
  scheduleAdvise --> callback2;
  callback2 -- No --> sendDocID;
  callback2 -- Yes --> add2subscribers;
  add2subscribers --> sendDocID;
```

**Comment by KPostOffice** [comment]
I think an important question is how we maintain the `list_of_subscribers`. This is something that we could technically maintain in user-api, however because of downtime and user-api being stateless we could lose subscriptions

**Comment by KPostOffice** [comment]
The current idea is to create a k8 secret associated with the document id. (i.e. callback-adviser-9asdfa9e) where each entry is the URL as a key and the callback data (which might contain client API secrets) is the value. When adviser finishes, this secret is mounted by a new step which takes adviser results and writes results back to all URLs found in the secret.

**Comment by harshad16** [comment]
This is completed and demo'ed
Thanks @KPostOffice for working on this.
closing the issue.
